<?xml version="1.0" encoding="UTF-8"?>
<?PowerDesigner AppLocale="UTF16" ID="{EFB2DB63-FCDC-4EBC-9B59-1305939F2FFC}" Label="" LastModificationDate="1488889228" Name="${project_name}" Objects="1788" Symbols="141" Target="MySQL 5.0" Type="{CDE44E21-9669-11D1-9914-006097355D9B}" signature="PDM_DATA_MODEL_XML" version="16.5.0.3982"?>
<!-- do not edit this file -->

<Model xmlns:a="attribute" xmlns:c="collection" xmlns:o="object">

    <o:RootObject Id="o1">
        <c:Children>
            <o:Model Id="o2">
                <a:ObjectID>EFB2DB63-FCDC-4EBC-9B59-1305939F2FFC</a:ObjectID>
                <a:Name>${project_name}</a:Name>
                <a:Code>${project_name}</a:Code>
                <a:CreationDate>1450232720</a:CreationDate>
                <a:Creator>Javashop</a:Creator>
                <a:ModificationDate>1482906139</a:ModificationDate>
                <a:Modifier>Javashop</a:Modifier>
                <a:PackageOptionsText>[FolderOptions]

                    [FolderOptions\Physical Objects]
                    GenerationCheckModel=Yes
                    GenerationPath=
                    GenerationOptions=
                    GenerationTasks=
                    GenerationTargets=
                    GenerationSelections=
                    RevPkey=Yes
                    RevFkey=Yes
                    RevAkey=Yes
                    RevCheck=Yes
                    RevIndx=Yes
                    RevOpts=Yes
                    RevViewAsTabl=No
                    RevViewOpts=Yes
                    RevSystAsTabl=Yes
                    RevTablPerm=No
                    RevViewPerm=No
                    RevProcPerm=No
                    RevDbpkPerm=No
                    RevSqncPerm=No
                    RevAdtPerm=No
                    RevUserPriv=No
                    RevUserOpts=No
                    RevGrpePriv=No
                    RevRolePriv=No
                    RevDtbsOpts=Yes
                    RevDtbsPerm=No
                    RevViewIndx=Yes
                    RevJidxOpts=Yes
                    RevStats=No
                    RevTspcPerm=No
                    RevCaseSensitive=No
                    GenTrgrStdMsg=Yes
                    GenTrgrMsgTab=
                    GenTrgrMsgNo=
                    GenTrgrMsgTxt=
                    TrgrPreserve=No
                    TrgrIns=Yes
                    TrgrUpd=Yes
                    TrgrDel=Yes
                    TrgrC2Ins=Yes
                    TrgrC2Upd=Yes
                    TrgrC3=Yes
                    TrgrC4=Yes
                    TrgrC5=Yes
                    TrgrC6=Yes
                    TrgrC7=Yes
                    TrgrC8=Yes
                    TrgrC9=Yes
                    TrgrC10=Yes
                    TrgrC11=Yes
                    TrgrC1=Yes
                    TrgrC12Ins=Yes
                    TrgrC12Upd=Yes
                    TrgrC13=Yes
                    UpdateTableStatistics=Yes
                    UpdateColumnStatistics=Yes

                    [FolderOptions\Physical Objects\Database Generation]
                    GenScriptName=crebas
                    GenScriptName0=
                    GenScriptName1=
                    GenScriptName2=
                    GenScriptName3=
                    GenScriptName4=
                    GenScriptName5=
                    GenScriptName6=
                    GenScriptName7=
                    GenScriptName8=
                    GenScriptName9=
                    GenPathName=
                    GenSingleFile=Yes
                    GenODBC=No
                    GenCheckModel=Yes
                    GenScriptPrev=Yes
                    GenArchiveModel=No
                    GenUseSync=No
                    GenSyncChoice=0
                    GenSyncArch=
                    GenSyncRmg=0

                    [FolderOptions\Physical Objects\Database Generation\Format]
                    GenScriptTitle=Yes
                    GenScriptNamLabl=No
                    GenScriptQDtbs=No
                    GenScriptQOwnr=Yes
                    GenScriptCase=0
                    GenScriptEncoding=ANSI
                    GenScriptNAcct=No
                    IdentifierDelimiter=&quot;

                    [FolderOptions\Physical Objects\Database Generation\Database]
                    Create=Yes
                    Open=Yes
                    Close=Yes
                    Drop=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\Database\Create]
                    Physical Options=Yes
                    Header=Yes
                    Footer=Yes

                    [FolderOptions\Physical Objects\Database Generation\Tablespace]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\Tablespace\Create]
                    Header=Yes
                    Footer=Yes

                    [FolderOptions\Physical Objects\Database Generation\Storage]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\User]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes
                    Privilege=No
                    Grant=Yes

                    [FolderOptions\Physical Objects\Database Generation\User\Create]
                    Physical Options=No

                    [FolderOptions\Physical Objects\Database Generation\Group]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes
                    Privilege=No

                    [FolderOptions\Physical Objects\Database Generation\Role]
                    Create=Yes
                    Drop=Yes
                    Privilege=No

                    [FolderOptions\Physical Objects\Database Generation\UserDefinedDataType]
                    Create=Yes
                    Comment=Yes
                    Drop=Yes

                    [FolderOptions\Physical Objects\Database Generation\UserDefinedDataType\Create]
                    Default value=Yes
                    Check=Yes

                    [FolderOptions\Physical Objects\Database Generation\AbstractDataType]
                    Create=Yes
                    Header=Yes
                    Footer=Yes
                    Drop=Yes
                    Comment=Yes
                    Install JAVA class=Yes
                    Remove JAVA class=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\Rule]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Default]
                    Create=Yes
                    Comment=Yes
                    Drop=Yes

                    [FolderOptions\Physical Objects\Database Generation\Sequence]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column]

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Table]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Table\Create]
                    Check=Yes
                    Physical Options=Yes
                    Header=Yes
                    Footer=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Table\Create\Check]
                    Constraint declaration=No

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Column]
                    User datatype=No
                    Default value=Yes
                    Check=Yes
                    Physical Options=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Column\Check]
                    Constraint declaration=No

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Key]

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Key\Primary key]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Key\Primary key\Create]
                    Constraint declaration=No
                    Physical Options=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Key\Alternate key]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Key\Alternate key\Create]
                    Constraint declaration=No
                    Physical Options=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Foreign key]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Foreign key\Create]
                    Constraint declaration=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Index]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Index\Create]
                    Constraint declaration=Yes
                    Physical Options=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Index\Filter]
                    Primary key=No
                    Foreign key=No
                    Alternate key=No
                    Cluster=Yes
                    Other=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Trigger]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Table&amp;&amp;Column\Trigger\Filter]
                    For insert=Yes
                    For update=Yes
                    For delete=Yes
                    For other=Yes

                    [FolderOptions\Physical Objects\Database Generation\View]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\View\Create]
                    Force Column list=No
                    Physical Options=Yes
                    Header=Yes
                    Footer=Yes

                    [FolderOptions\Physical Objects\Database Generation\View\ViewColumn]
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\View\ViewIndex]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\View\ViewIndex\Create]
                    Physical Options=Yes

                    [FolderOptions\Physical Objects\Database Generation\View\ViewIndex\Filter]
                    Cluster=Yes
                    Other=Yes

                    [FolderOptions\Physical Objects\Database Generation\View\Trigger]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\View\Trigger\Filter]
                    For insert=Yes
                    For update=Yes
                    For delete=Yes
                    For other=Yes

                    [FolderOptions\Physical Objects\Database Generation\DBMSTrigger]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Synonym]
                    Create=Yes
                    Drop=Yes

                    [FolderOptions\Physical Objects\Database Generation\Synonym\Filter]
                    Table=Yes
                    View=Yes
                    Proc=Yes
                    Synonym=Yes
                    Database Package=Yes
                    Sequence=Yes

                    [FolderOptions\Physical Objects\Database Generation\JoinIndex]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\JoinIndex\Create]
                    Physical Options=Yes
                    Header=Yes
                    Footer=Yes

                    [FolderOptions\Physical Objects\Database Generation\Procedure]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\Procedure\Create]
                    Header=Yes
                    Footer=Yes

                    [FolderOptions\Physical Objects\Database Generation\DatabasePackage]
                    Create=Yes
                    Drop=Yes
                    Permission=No

                    [FolderOptions\Physical Objects\Database Generation\WebService]
                    Create=Yes
                    Drop=Yes
                    Comment=Yes

                    [FolderOptions\Physical Objects\Database Generation\Dimension]
                    Create=Yes
                    Drop=Yes

                    [FolderOptions\Physical Objects\Database Generation\Synchronization]
                    GenBackupTabl=1
                    GenKeepBackTabl=1
                    GenTmpTablDrop=No
                    GenKeepTablOpts=No

                    [FolderOptions\Physical Objects\Test Data]
                    GenDataPathName=
                    GenDataSinglefile=Yes
                    GenDataScriptName=testdata
                    GenDataScriptName0=
                    GenDataScriptName1=
                    GenDataScriptName2=
                    GenDataScriptName3=
                    GenDataScriptName4=
                    GenDataScriptName5=
                    GenDataScriptName6=
                    GenDataScriptName7=
                    GenDataScriptName8=
                    GenDataScriptName9=
                    GenDataOdbc=0
                    GenDataDelOld=No
                    GenDataTitle=No
                    GenDataDefNumRows=20
                    GenDataCommit=0
                    GenDataPacket=0
                    GenDataOwner=No
                    GenDataProfNumb=
                    GenDataProfChar=
                    GenDataProfDate=
                    GenDataCSVSeparator=,
                    GenDataFileFormat=CSV
                    GenDataUseWizard=No

                    [FolderOptions\Pdm]
                    IndxIQName=%COLUMN%_%INDEXTYPE%
                    IndxPK=Yes
                    IndxFK=Yes
                    IndxAK=Yes
                    IndxPKName=%TABLE%_PK
                    IndxFKName=%REFR%_FK
                    IndxAKName=%AKEY%_AK
                    IndxPreserve=No
                    IndxThreshold=0
                    IndxStats=No
                    RefrPreserve=No
                    JidxPreserve=No
                    RbldMultiFact=Yes
                    RbldMultiDim=Yes
                    RbldMultiJidx=Yes
                    CubePreserve=No
                    TablStProcPreserve=No
                    ProcDepPreserve=Yes
                    TrgrDepPreserve=Yes
                    CubeScriptPath=
                    CubeScriptCase=0
                    CubeScriptEncoding=ANSI
                    CubeScriptNacct=No
                    CubeScriptHeader=No
                    CubeScriptExt=csv
                    CubeScriptExt0=txt
                    CubeScriptExt1=
                    CubeScriptExt2=
                    CubeScriptSep=,
                    CubeScriptDeli=&quot;
                    EstimationYears=0
                    DfltDomnName=D_%.U:VALUE%
                    DfltColnName=D_%.U:VALUE%
                    DfltReuse=Yes
                    DfltDrop=Yes</a:PackageOptionsText>
                <a:ModelOptionsText>[ModelOptions]

                    [ModelOptions\Physical Objects]
                    CaseSensitive=No
                    DisplayName=Yes
                    EnableTrans=No
                    UseTerm=No
                    EnableRequirements=No
                    EnableFullShortcut=No
                    DefaultDttp=
                    IgnoreOwner=No
                    RebuildTrigger=Yes
                    RefrUnique=No
                    RefrAutoMigrate=Yes
                    RefrMigrateReuse=Yes
                    RefrMigrateDomain=Yes
                    RefrMigrateCheck=Yes
                    RefrMigrateRule=Yes
                    RefrMigrateExtd=No
                    RefrMigrDefaultLink=No
                    RefrDfltImpl=D
                    RefrPrgtColn=No
                    RefrMigrateToEnd=No
                    RebuildTriggerDep=No
                    ColnFKName=%.3:PARENT%_%COLUMN%
                    ColnFKNameUse=No
                    DomnCopyDttp=Yes
                    DomnCopyChck=No
                    DomnCopyRule=No
                    DomnCopyMand=No
                    DomnCopyExtd=No
                    DomnCopyProf=No
                    Notation=0
                    DomnDefaultMandatory=No
                    ColnDefaultMandatory=No
                    TablDefaultOwner=
                    ViewDefaultOwner=
                    TrgrDefaultOwnerTabl=
                    TrgrDefaultOwnerView=
                    IdxDefaultOwnerTabl=
                    IdxDefaultOwnerView=
                    JdxDefaultOwner=
                    DBPackDefaultOwner=
                    SeqDefaultOwner=
                    ProcDefaultOwner=
                    DBMSTrgrDefaultOwner=
                    Currency=USD
                    RefrDeleteConstraint=1
                    RefrUpdateConstraint=1
                    RefrParentMandatory=No
                    RefrParentChangeAllow=Yes
                    RefrCheckOnCommit=No

                    [ModelOptions\Physical Objects\NamingOptionsTemplates]

                    [ModelOptions\Physical Objects\ClssNamingOptions]

                    [ModelOptions\Physical Objects\ClssNamingOptions\PDMPCKG]

                    [ModelOptions\Physical Objects\ClssNamingOptions\PDMPCKG\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\PDMPCKG\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\PDMDOMN]

                    [ModelOptions\Physical Objects\ClssNamingOptions\PDMDOMN\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\PDMDOMN\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\TABL]

                    [ModelOptions\Physical Objects\ClssNamingOptions\TABL\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\TABL\Code]
                    Template=
                    MaxLen=64
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\COLN]

                    [ModelOptions\Physical Objects\ClssNamingOptions\COLN\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\COLN\Code]
                    Template=
                    MaxLen=64
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\INDX]

                    [ModelOptions\Physical Objects\ClssNamingOptions\INDX\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\INDX\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\REFR]

                    [ModelOptions\Physical Objects\ClssNamingOptions\REFR\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\REFR\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\VREF]

                    [ModelOptions\Physical Objects\ClssNamingOptions\VREF\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\VREF\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\VIEW]

                    [ModelOptions\Physical Objects\ClssNamingOptions\VIEW\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\VIEW\Code]
                    Template=
                    MaxLen=64
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\VIEWC]

                    [ModelOptions\Physical Objects\ClssNamingOptions\VIEWC\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\VIEWC\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\WEBSERV]

                    [ModelOptions\Physical Objects\ClssNamingOptions\WEBSERV\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\WEBSERV\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=&#39;a&#39;-&#39;z&#39;,&#39;A&#39;-&#39;Z&#39;,&#39;0&#39;-&#39;9&#39;,&quot;/-_.!~*&#39;()&quot;
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\WEBOP]

                    [ModelOptions\Physical Objects\ClssNamingOptions\WEBOP\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\WEBOP\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=&#39;a&#39;-&#39;z&#39;,&#39;A&#39;-&#39;Z&#39;,&#39;0&#39;-&#39;9&#39;,&quot;/-_.!~*&#39;()&quot;
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\WPARAM]

                    [ModelOptions\Physical Objects\ClssNamingOptions\WPARAM\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\WPARAM\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FACT]

                    [ModelOptions\Physical Objects\ClssNamingOptions\FACT\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FACT\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\DIMN]

                    [ModelOptions\Physical Objects\ClssNamingOptions\DIMN\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\DIMN\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\MEAS]

                    [ModelOptions\Physical Objects\ClssNamingOptions\MEAS\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\MEAS\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\DATTR]

                    [ModelOptions\Physical Objects\ClssNamingOptions\DATTR\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\DATTR\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FILO]

                    [ModelOptions\Physical Objects\ClssNamingOptions\FILO\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FILO\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FRMEOBJ]

                    [ModelOptions\Physical Objects\ClssNamingOptions\FRMEOBJ\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FRMEOBJ\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FRMELNK]

                    [ModelOptions\Physical Objects\ClssNamingOptions\FRMELNK\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\FRMELNK\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\DefaultClass]

                    [ModelOptions\Physical Objects\ClssNamingOptions\DefaultClass\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\DefaultClass\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\CUBE]

                    [ModelOptions\Physical Objects\ClssNamingOptions\CUBE\Name]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Physical Objects\ClssNamingOptions\CUBE\Code]
                    Template=
                    MaxLen=254
                    Case=M
                    ValidChar=
                    InvldChar=
                    AllValid=Yes
                    NoAccent=No
                    DefaultChar=
                    Script=
                    ConvTable=
                    ConvTablePath=%_HOME%\Resource Files\Conversion Tables

                    [ModelOptions\Connection]

                    [ModelOptions\Pdm]

                    [ModelOptions\Generate]

                    [ModelOptions\Generate\Xsm]
                    GenRootElement=Yes
                    GenComplexType=No
                    GenAttribute=Yes
                    CheckModel=Yes
                    SaveLinks=Yes
                    ORMapping=No
                    NameToCode=No

                    [ModelOptions\Generate\Pdm]
                    RRMapping=No

                    [ModelOptions\Generate\Cdm]
                    CheckModel=Yes
                    SaveLinks=Yes
                    NameToCode=No
                    Notation=2

                    [ModelOptions\Generate\Oom]
                    CheckModel=Yes
                    SaveLinks=Yes
                    ORMapping=No
                    NameToCode=Yes
                    ClassPrefix=

                    [ModelOptions\Generate\Ldm]
                    CheckModel=Yes
                    SaveLinks=Yes
                    NameToCode=No

                    [ModelOptions\Default Opts]

                    [ModelOptions\Default Opts\TABL]
                    PhysOpts=

                    [ModelOptions\Default Opts\COLN]
                    PhysOpts=

                    [ModelOptions\Default Opts\INDX]
                    PhysOpts=

                    [ModelOptions\Default Opts\AKEY]
                    PhysOpts=

                    [ModelOptions\Default Opts\PKEY]
                    PhysOpts=

                    [ModelOptions\Default Opts\STOR]
                    PhysOpts=

                    [ModelOptions\Default Opts\TSPC]
                    PhysOpts=

                    [ModelOptions\Default Opts\SQNC]
                    PhysOpts=

                    [ModelOptions\Default Opts\DTBS]
                    PhysOpts=

                    [ModelOptions\Default Opts\USER]
                    PhysOpts=

                    [ModelOptions\Default Opts\JIDX]
                    PhysOpts=</a:ModelOptionsText>
                <c:DBMS>
                    <o:Shortcut Id="o3">
                        <a:ObjectID>E9865CE0-9560-41F3-81D1-267B57C4DA8F</a:ObjectID>
                        <a:Name>MySQL 5.0</a:Name>
                        <a:Code>MYSQL50</a:Code>
                        <a:CreationDate>1450232718</a:CreationDate>
                        <a:Creator>Administrator</a:Creator>
                        <a:ModificationDate>1450232718</a:ModificationDate>
                        <a:Modifier>Administrator</a:Modifier>
                        <a:TargetStereotype/>
                        <a:TargetID>F4F16ECD-F2F1-4006-AF6F-638D5C65F35E</a:TargetID>
                        <a:TargetClassID>4BA9F647-DAB1-11D1-9944-006097355D9B</a:TargetClassID>
                    </o:Shortcut>
                </c:DBMS>
                <c:PhysicalDiagrams>
                    ${pysicalDiagrams}
                </c:PhysicalDiagrams>
                <c:DefaultDiagram>
                    <o:PhysicalDiagram Ref="o4"/>
                </c:DefaultDiagram>
                <c:Tables>
                    ${tables}
                </c:Tables>
                <c:DefaultGroups>
                    <o:Group Id="o1745">
                        <a:ObjectID>FA1EDDCE-549A-4210-9025-F72ED1DF0072</a:ObjectID>
                        <a:Name>PUBLIC</a:Name>
                        <a:Code>PUBLIC</a:Code>
                        <a:CreationDate>1450232718</a:CreationDate>
                        <a:Creator>Administrator</a:Creator>
                        <a:ModificationDate>1450232718</a:ModificationDate>
                        <a:Modifier>Administrator</a:Modifier>
                    </o:Group>
                </c:DefaultGroups>
                <c:TargetModels>
                    <o:TargetModel Id="o1746">
                        <a:ObjectID>DA7DDA93-74E0-42D0-A38F-2BD44ECE440F</a:ObjectID>
                        <a:Name>MySQL 5.0</a:Name>
                        <a:Code>MYSQL50</a:Code>
                        <a:CreationDate>1450232718</a:CreationDate>
                        <a:Creator>Administrator</a:Creator>
                        <a:ModificationDate>1488889228</a:ModificationDate>
                        <a:Modifier>javashop</a:Modifier>
                        <a:TargetModelURL>file:///%_DBMS%/mysql50.xdb</a:TargetModelURL>
                        <a:TargetModelID>F4F16ECD-F2F1-4006-AF6F-638D5C65F35E</a:TargetModelID>
                        <a:TargetModelClassID>4BA9F647-DAB1-11D1-9944-006097355D9B</a:TargetModelClassID>
                        <a:TargetModelLastModificationDate>1276524678</a:TargetModelLastModificationDate>
                        <c:SessionShortcuts>
                            <o:Shortcut Ref="o3"/>
                        </c:SessionShortcuts>
                    </o:TargetModel>
                </c:TargetModels>
            </o:Model>
        </c:Children>
    </o:RootObject>

</Model>